
services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MONGO_URL=mongodb://mongo:27017/lims
    depends_on:
      - postgres
      - mongo
    ports:
      - "8000:8000"
    networks:
      - lims-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - lims-network
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lims-network
  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    networks:
      - lims-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - lims-network
volumes:
  postgres-data:
  mongo-data:
networks:
  lims-network:
    driver: bridge